site_name: MkRefs
site_description: MkRefs Plugin â€“ semantic references for research tools
site_url: https://github.com/DerwenAI/mkrefs

mkrefs_config: mkrefs.yml

nav:
    - Home: index.md
    - Other: other.md
    - Reference: ref.md
    - Glossary: glossary.md
    - Bibliography: biblio.md

plugins:
  - mkrefs
